<?php

declare(strict_types=1);

namespace Bolt\Extension;

use Bolt\Common\Str;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Yaml\Yaml;
use Webmozart\PathUtil\Path;

class ExtensionCompilerPass implements CompilerPassInterface
{
    /** string */
    private $projectDir;

    public function process(ContainerBuilder $container): void
    {
        if ($container->has(ExtensionRegistry::class) === false) {
            return;
        }

        $registry = $container->findDefinition(ExtensionRegistry::class);
        $packages = array_keys($container->findTaggedServiceIds(ExtensionInterface::CONTAINER_TAG));
        $this->projectDir = $container->getParameter('kernel.project_dir');

        /* @see ExtensionRegistry::addCompilerPass() */
        $registry->addMethodCall('addCompilerPass', [$packages]);

        // Rebuild our own `services_bolt.yml` file.
        $this->buildServices($packages);
    }

    public function buildServices(array $packages): void
    {
        $services = [
            'services' => [
                '_defaults' => [
                    'autowire' => true,
                    'autoconfigure' => true,
                ],
            ],
        ];

        foreach ($packages as $package) {
            [$name, $service] = $this->createService($package);
            if ($name) {
                $services['services'][$name] = $service;
            }
        }

        $yaml = "# This file is auto-generated by Bolt. Do not modify.\n\n";
        $yaml .= Yaml::dump($services, 3);

        $filename = $this->projectDir . '/config/services_bolt.yaml';
        file_put_contents($filename, $yaml);
    }

    private function createService(string $package): array
    {
        $reflection = new \ReflectionClass($package);

        $namespace = Str::removeLast($reflection->getName(), Str::splitLast($reflection->getName(), '\\'));
        $path = Path::makeRelative(dirname($reflection->getFileName()), $this->projectDir . '/foo');

        return [$namespace, [
            'resource' => $path . '/*',
            'exclude' => $path . '/{Entity,Exception}',
        ]];
    }
}
