name: Test Database migration

on:
    pull_request:


jobs:
    db_migration:
        strategy:
            matrix:
                php-version: [ '8.1' ]
                db-source-version: ['4.2', '5.0', '5.1']
#                db-source-version: ['4.2']
            fail-fast: false
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - "3306:3306"
                env:
                    MYSQL_DATABASE: bolt
                    MYSQL_USER: bolt
                    MYSQL_PASSWORD: bolt
                    MYSQL_ROOT_PASSWORD: bolt
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
                
        name: DB Migration test from ${{ matrix.db-source-version }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: restore database
              run: mysql -h 127.0.0.1 -u root --password=bolt bolt < tests/assets/database_dump/bolt-${{ matrix.db-source-version }}_database.sql
            
            - uses: shivammathur/setup-php@v2
              with:
                  # test the lowest version, to make sure checks pass on it
                  php-version: ${{ matrix.php-version }}
                  extensions: json, mbstring, pdo, curl, pdo_sqlite
                  coverage: none
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Install composer dependencies
              run: composer install --prefer-dist --no-progress
              env:
                  DATABASE_URL: mysql://bolt:bolt@127.0.0.1/bolt?serverVersion=5.7&charset=utf8mb4
              
            - name: upgrade
              run: bin/console doctrine:migrations:migrate -n
              env:
                  DATABASE_URL: mysql://bolt:bolt@127.0.0.1/bolt?serverVersion=5.7&charset=utf8mb4
              
            - name: list migration
              run: |
                bin/console doctrine:migration:status -n
                bin/console doctrine:migration:list -n
              env:
                  DATABASE_URL: mysql://bolt:bolt@127.0.0.1/bolt?serverVersion=5.7&charset=utf8mb4
              
            - name: check if update is needed
              run: bin/console doctrine:migrations:diff -n
              env:
                  DATABASE_URL: mysql://bolt:bolt@127.0.0.1/bolt?serverVersion=5.7&charset=utf8mb4
