name: Unit Tests Checks

on:
  pull_request:

env:
  COMPOSER_CACHE_DIR: /tmp/composer-cache

jobs:
  unittests:
    strategy:
      matrix:
        php-version: [ '8.2', '8.3', '8.4' ]
      fail-fast: false
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          # test the lowest version, to make sure checks pass on it
          php-version: ${{ matrix.php-version }}
          extensions: json, mbstring, pdo, curl, pdo_sqlite
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
      - run: composer install --no-progress --no-interaction
      - name: run PHP Unit
        run: ./vendor/bin/phpunit
